name: Build, Push to Docker Hub, and Deploy Node.js App

on:
  push:
    branches: [ main ]

jobs:
  docker-on-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sample-node-app:latest

      - name: Stop and remove previous container (if exists)
        run: |
          docker stop app || true
          docker rm app || true

      - name: Pull image from Docker Hub and run container
        run: |
          docker run -d -p 3000:3000 --name app ${{ secrets.DOCKER_USERNAME }}/sample-node-app:latest

      - name: Wait for server to start
        run: sleep 5

      - name: Test app on localhost
        run: curl http://localhost:3000

      - name: Show Docker logs
        run: docker logs app
